# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 00:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20170317_0136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': (('single_person', 'Can only view their own person record'),), 'verbose_name': 'SPm1 person', 'verbose_name_plural': 'SPm2 people'},
        ),
    ]
