# Generated by Django 2.0.1 on 2018-01-08 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_auto_20170321_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='based_at',
            field=models.ForeignKey(blank=True, help_text='Link to a primary hospital location for the member of staff', null=True, on_delete=django.db.models.deletion.PROTECT, to='locations.Hospital', verbose_name='SP02 location'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
