# Generated by Django 2.0.4 on 2018-04-03 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_auto_20180108_1433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['id'], 'permissions': (('single_person', 'Can only view their own person record'),), 'verbose_name': 'SPm1 person', 'verbose_name_plural': 'SPm2 people'},
        ),
    ]
