# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 15:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adverse_event', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compare', '0002_retrievalteam_based_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='contact',
            field=models.ForeignKey(help_text='AEh09 This should be the Local Investigator for the Transplant Centre', on_delete=django.db.models.deletion.CASCADE, related_name='adverse_event_contact', to=settings.AUTH_USER_MODEL, verbose_name='AE09 primary contact'),
        ),
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(help_text='User account for the person logged in when this record was made/updated', on_delete=django.db.models.deletion.CASCADE, related_name='adverse_event_event_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='organ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compare.Organ', verbose_name='AE04 trial id link'),
        ),
        migrations.AddField(
            model_name='category',
            name='created_by',
            field=models.ForeignKey(help_text='User account for the person logged in when this record was made/updated', on_delete=django.db.models.deletion.CASCADE, related_name='adverse_event_category_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterOrderWithRespectTo(
            name='event',
            order_with_respect_to='organ',
        ),
    ]
