# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverse_event', '0002_auto_20170215_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='categories',
            field=models.ManyToManyField(to='adverse_event.Category'),
        ),
    ]
