# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 19:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adverse_event', '0002_auto_20160106_1513'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlternativeGrading',
        ),
        migrations.DeleteModel(
            name='ClavienDindoGrading',
        ),
        migrations.RemoveField(
            model_name='adverseevent',
            name='device_related',
        ),
        migrations.RemoveField(
            model_name='adverseevent',
            name='resolution_at_date',
        ),
        migrations.RemoveField(
            model_name='adverseevent',
            name='sequence_number',
        ),
        migrations.AddField(
            model_name='adverseevent',
            name='admitted_to_itu',
            field=models.BooleanField(default=False, verbose_name='AE33 admitted to ITU'),
        ),
        migrations.AddField(
            model_name='adverseevent',
            name='alive_query_1',
            field=models.BooleanField(default=False, verbose_name='AE20 incapcity'),
        ),
        migrations.AddField(
            model_name='adverseevent',
            name='alive_query_2',
            field=models.BooleanField(default=False, verbose_name='AE21 usual activity'),
        ),
        migrations.AddField(
            model_name='adverseevent',
            name='alive_query_3',
            field=models.BooleanField(default=False, verbose_name='AE22 no sequelae'),
        ),
        migrations.AddField(
            model_name='adverseevent',
            name='alive_query_4',
            field=models.BooleanField(default=False, verbose_name='AE23 device deficiency'),
        ),
        migrations.AddField(
            model_name='adverseevent',
            name='alive_query_5',
            field=models.BooleanField(default=False, verbose_name='AE24 device user error'),
        ),
        migrations.AddField(
            model_name='adverseevent',
            name='alive_query_6',
            field=models.BooleanField(default=False, verbose_name='AE25 life threatening illness'),
        ),
        migrations.AddField(
            model_name='adverseevent',
            name='alive_query_7',
            field=models.BooleanField(default=False, verbose_name='AE26 permanent impairment'),
        ),
        migrations.AddField(
            model_name='adverseevent',
            name='alive_query_8',
            field=models.BooleanField(default=False, verbose_name='AE27 prolonged hospitalisation'),
        ),
        migrations.AddField(
            model_name='adverseevent',
            name='alive_query_9',
            field=models.BooleanField(default=False, verbose_name='AE28 surgery required'),
        ),
        migrations.AddField(
            model_name='adverseevent',
            name='biopsy_taken',
            field=models.BooleanField(default=False, verbose_name='AE35 admitted to ITU'),
        ),
        migrations.AddField(
            model_name='adverseevent',
            name='cause_of_death_1',
            field=models.BooleanField(default=False, verbose_name='AE42 cerebrovascular'),
        ),
        migrations.AddField(
            model_name='adverseevent',
            name='cause_of_death_2',
            field=models.BooleanField(default=False, verbose_name='AE43 multi organ'),
        ),
        migrations.AddField(
            model_name='adverseevent',
            name='cause_of_death_3',
            field=models.BooleanField(default=False, verbose_name='AE44 pneumonia'),
        ),
        migrations.AddField(
            model_name='adverseevent',
            name='cause_of_death_4',
            field=models.BooleanField(default=False, verbose_name='AE45 sepsis'),
        ),
        migrations.AddField(
            model_name='adverseevent',
            name='cause_of_death_5',
            field=models.BooleanField(default=False, verbose_name='AE46 transplant related'),
        ),
        migrations.AddField(
            model_name='adverseevent',
            name='cause_of_death_6',
            field=models.BooleanField(default=False, verbose_name='AE47 other'),
        ),
        migrations.AddField(
            model_name='adverseevent',
            name='cause_of_death_comment',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='AE48 comments'),
        ),
        migrations.AddField(
            model_name='adverseevent',
            name='date_of_admission',
            field=models.DateField(blank=True, null=True, verbose_name='AE31 date of admission'),
        ),
        migrations.AddField(
            model_name='adverseevent',
            name='date_of_death',
            field=models.DateField(blank=True, null=True, verbose_name='AE41 date of death'),
        ),
        migrations.AddField(
            model_name='adverseevent',
            name='date_of_discharge',
            field=models.DateField(blank=True, null=True, verbose_name='AE32 date of discharge'),
        ),
        migrations.AddField(
            model_name='adverseevent',
            name='death',
            field=models.BooleanField(default=False, verbose_name='AE40 led to death'),
        ),
        migrations.AddField(
            model_name='adverseevent',
            name='dialysis_needed',
            field=models.BooleanField(default=False, verbose_name='AE34 admitted to ITU'),
        ),
        migrations.AddField(
            model_name='adverseevent',
            name='event_ongoing',
            field=models.BooleanField(default=True, verbose_name='AE03 event ongoing'),
        ),
        migrations.AddField(
            model_name='adverseevent',
            name='rehospitalisation',
            field=models.BooleanField(default=False, verbose_name='AE30 incapcity'),
        ),
        migrations.AddField(
            model_name='adverseevent',
            name='rehospitalisation_comments',
            field=models.TextField(blank=True, null=True, verbose_name='AE37 comments'),
        ),
        migrations.AddField(
            model_name='adverseevent',
            name='serious_eligible_1',
            field=models.BooleanField(default=False, verbose_name='AE10 lead to death'),
        ),
        migrations.AddField(
            model_name='adverseevent',
            name='serious_eligible_2',
            field=models.BooleanField(default=False, verbose_name='AE11 life threatening illness'),
        ),
        migrations.AddField(
            model_name='adverseevent',
            name='serious_eligible_3',
            field=models.BooleanField(default=False, verbose_name='AE12 permanent impairment'),
        ),
        migrations.AddField(
            model_name='adverseevent',
            name='serious_eligible_4',
            field=models.BooleanField(default=False, verbose_name='AE13 hospitalisation'),
        ),
        migrations.AddField(
            model_name='adverseevent',
            name='serious_eligible_5',
            field=models.BooleanField(default=False, verbose_name='AE14 prolonged hospitalisation'),
        ),
        migrations.AddField(
            model_name='adverseevent',
            name='serious_eligible_6',
            field=models.BooleanField(default=False, verbose_name='AE15 surgery required'),
        ),
        migrations.AddField(
            model_name='adverseevent',
            name='surgery_required',
            field=models.BooleanField(default=False, verbose_name='AE36 surgery required'),
        ),
        migrations.AddField(
            model_name='adverseevent',
            name='treatment_related',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2, 'MMc03 Unknown'), (0, 'MMc01 No'), (1, 'MMc02 Yes')], null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='adverseevent',
            name='created_by',
            field=models.ForeignKey(help_text='User account for the person logged in when this record was made/updated', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='adverseevent',
            name='organ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compare.Organ', verbose_name='AE04 trial id link'),
        ),
        migrations.AlterField(
            model_name='adverseevent',
            name='record_locked',
            field=models.BooleanField(default=False, help_text='Not presently implemented or used'),
        ),
        migrations.AlterField(
            model_name='adverseevent',
            name='version',
            field=models.PositiveIntegerField(default=0, help_text='Internal tracking version number'),
        ),
    ]
