# Generated by Django 2.0.1 on 2018-01-08 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adverse_event', '0002_auto_20170317_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='contact',
            field=models.ForeignKey(help_text='AEh09 This should be the Local Investigator for the Transplant Centre', on_delete=django.db.models.deletion.PROTECT, related_name='adverse_event_contact', to=settings.AUTH_USER_MODEL, verbose_name='AE09 primary contact'),
        ),
        migrations.AlterField(
            model_name='event',
            name='organ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compare.Organ', verbose_name='AE04 trial id link'),
        ),
    ]
