# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverse_event', '0003_auto_20160427_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adverseevent',
            name='action',
            field=models.TextField(blank=True, null=True, verbose_name='AE07 action'),
        ),
        migrations.AlterField(
            model_name='adverseevent',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='AE06 description'),
        ),
        migrations.AlterField(
            model_name='adverseevent',
            name='outcome',
            field=models.TextField(blank=True, null=True, verbose_name='AE08 outcome'),
        ),
        migrations.AlterField(
            model_name='adverseevent',
            name='rehospitalisation',
            field=models.BooleanField(default=False, verbose_name='AE30 rehospitalisation'),
        ),
        migrations.AlterField(
            model_name='adverseevent',
            name='treatment_related',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2, 'MMc03 Unknown'), (0, 'MMc01 No'), (1, 'MMc02 Yes')], null=True, verbose_name='AE49 treatment related?'),
        ),
    ]
