# Generated by Django 2.1.7 on 2019-02-22 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adverse_event', '0003_auto_20180108_1433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': (('restrict_to_national', 'Can only use data from the same location country'), ('restrict_to_local', 'Can only use data from a specific location')), 'verbose_name': 'AEm1 adverse event', 'verbose_name_plural': 'AEm2 adverse events'},
        ),
    ]
