# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverse_event', '0004_auto_20160428_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adverseevent',
            name='biopsy_taken',
            field=models.BooleanField(default=False, verbose_name='AE35 biopsy taken'),
        ),
        migrations.AlterField(
            model_name='adverseevent',
            name='dialysis_needed',
            field=models.BooleanField(default=False, verbose_name='AE34 dialysis needed'),
        ),
    ]
