# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 15:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import livefield.fields
import wp4.compare.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QualityOfLife',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('version', models.PositiveIntegerField(default=0, help_text='Internal tracking version number')),
                ('record_locked', models.BooleanField(default=False, help_text='Not presently implemented or used')),
                ('live', livefield.fields.LiveField(default=True)),
                ('date_recorded', models.DateField(blank=True, help_text='Date can not be in the future', null=True, validators=[wp4.compare.validators.validate_not_in_future], verbose_name='QL07 date recorded')),
                ('qol_mobility', models.PositiveSmallIntegerField(blank=True, help_text='Answer must be in range 1-5', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='QL01 qol mobility score')),
                ('qol_selfcare', models.PositiveSmallIntegerField(blank=True, help_text='Answer must be in range 1-5', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='QL02 qol self care score')),
                ('qol_usual_activities', models.PositiveSmallIntegerField(blank=True, help_text='Answer must be in range 1-5', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='QL03 qol usual activites score')),
                ('qol_pain', models.PositiveSmallIntegerField(blank=True, help_text='Answer must be in range 1-5', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='QL04 qol pain or discomfort score')),
                ('qol_anxiety', models.PositiveSmallIntegerField(blank=True, help_text='Answer must be in range 1-5', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='QL05 qol anxiety or depression score')),
                ('vas_score', models.PositiveSmallIntegerField(blank=True, help_text='Answer must be in range 0-100', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='QL06 vas score')),
            ],
            options={
                'verbose_name': 'QLm1 Quality of Life record',
                'abstract': False,
                'permissions': (('view', 'Can view the data, but not modify it'), ('restrict_to_national', 'Can only use data from the same location country'), ('restrict_to_local', 'Can only use data from a specific location')),
                'verbose_name_plural': 'QLm2 Quality of Life records',
            },
        ),
        migrations.CreateModel(
            name='ResourceHospitalAdmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='RH01 reason')),
                ('had_surgery', models.NullBooleanField(verbose_name='RH02 had surgery')),
                ('days_in_itu', models.PositiveSmallIntegerField(default=0, verbose_name='RH03 days in itu')),
                ('days_in_hospital', models.PositiveSmallIntegerField(default=1, verbose_name='RH04 days in hospital')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResourceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('version', models.PositiveIntegerField(default=0, help_text='Internal tracking version number')),
                ('record_locked', models.BooleanField(default=False, help_text='Not presently implemented or used')),
                ('live', livefield.fields.LiveField(default=True)),
                ('date_given', models.DateField(blank=True, help_text='Date can not be in the future', null=True, validators=[wp4.compare.validators.validate_not_in_future], verbose_name='RL01 date given')),
                ('date_returned', models.DateField(blank=True, help_text='Date can not be in the future', null=True, validators=[wp4.compare.validators.validate_not_in_future], verbose_name='RL02 date returned')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='RL03 notes')),
            ],
            options={
                'verbose_name': 'RLm1 Resource Usage Log',
                'abstract': False,
                'permissions': (('view', 'Can view the data, but not modify it'), ('restrict_to_national', 'Can only use data from the same location country'), ('restrict_to_local', 'Can only use data from a specific location')),
                'verbose_name_plural': 'RLm2 Resource Usage Logs',
            },
        ),
        migrations.CreateModel(
            name='ResourceRehabilitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='RR01 reason')),
                ('days_in_hospital', models.PositiveSmallIntegerField(default=1, verbose_name='RR02 days in hospital')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResourceVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'RVc01 appointment at GP'), (2, 'RVc02 GP visited'), (3, 'RVc03 appointment at specialist'), (4, 'RVc04 A&E')], verbose_name='RV01 visit type')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
