# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 15:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compare', '0003_auto_20170215_1527'),
        ('health_economics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcevisit',
            name='created_by',
            field=models.ForeignKey(help_text='User account for the person logged in when this record was made/updated', on_delete=django.db.models.deletion.CASCADE, related_name='health_economics_resourcevisit_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resourcevisit',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health_economics.ResourceLog'),
        ),
        migrations.AddField(
            model_name='resourcerehabilitation',
            name='created_by',
            field=models.ForeignKey(help_text='User account for the person logged in when this record was made/updated', on_delete=django.db.models.deletion.CASCADE, related_name='health_economics_resourcerehabilitation_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resourcerehabilitation',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health_economics.ResourceLog'),
        ),
        migrations.AddField(
            model_name='resourcelog',
            name='created_by',
            field=models.ForeignKey(help_text='User account for the person logged in when this record was made/updated', on_delete=django.db.models.deletion.CASCADE, related_name='health_economics_resourcelog_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resourcelog',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compare.Recipient'),
        ),
        migrations.AddField(
            model_name='resourcehospitaladmission',
            name='created_by',
            field=models.ForeignKey(help_text='User account for the person logged in when this record was made/updated', on_delete=django.db.models.deletion.CASCADE, related_name='health_economics_resourcehospitaladmission_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resourcehospitaladmission',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health_economics.ResourceLog'),
        ),
        migrations.AddField(
            model_name='qualityoflife',
            name='created_by',
            field=models.ForeignKey(help_text='User account for the person logged in when this record was made/updated', on_delete=django.db.models.deletion.CASCADE, related_name='health_economics_qualityoflife_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qualityoflife',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compare.Recipient'),
        ),
    ]
