# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 19:38
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import wp4.compare.validators


class Migration(migrations.Migration):

    dependencies = [
        ('health_economics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualityoflife',
            name='date_recorded',
            field=models.DateField(blank=True, help_text='Date can not be in the future', null=True, validators=[wp4.compare.validators.validate_not_in_future], verbose_name='QL07 date recorded'),
        ),
        migrations.AlterField(
            model_name='qualityoflife',
            name='created_by',
            field=models.ForeignKey(help_text='User account for the person logged in when this record was made/updated', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='qualityoflife',
            name='qol_anxiety',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Answer must be in range 1-5', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='QL05 qol anxiety or depression score'),
        ),
        migrations.AlterField(
            model_name='qualityoflife',
            name='qol_mobility',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Answer must be in range 1-5', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='QL01 qol mobility score'),
        ),
        migrations.AlterField(
            model_name='qualityoflife',
            name='qol_pain',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Answer must be in range 1-5', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='QL04 qol pain or discomfort score'),
        ),
        migrations.AlterField(
            model_name='qualityoflife',
            name='qol_selfcare',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Answer must be in range 1-5', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='QL02 qol self care score'),
        ),
        migrations.AlterField(
            model_name='qualityoflife',
            name='qol_usual_activities',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Answer must be in range 1-5', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='QL03 qol usual activites score'),
        ),
        migrations.AlterField(
            model_name='qualityoflife',
            name='recipient',
            field=models.ForeignKey(help_text='Internal link to the Recipient', on_delete=django.db.models.deletion.CASCADE, to='compare.Recipient'),
        ),
        migrations.AlterField(
            model_name='qualityoflife',
            name='record_locked',
            field=models.BooleanField(default=False, help_text='Not presently implemented or used'),
        ),
        migrations.AlterField(
            model_name='qualityoflife',
            name='vas_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Answer must be in range 0-100', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='QL06 vas score'),
        ),
        migrations.AlterField(
            model_name='qualityoflife',
            name='version',
            field=models.PositiveIntegerField(default=0, help_text='Internal tracking version number'),
        ),
    ]
