# Generated by Django 2.1.7 on 2019-02-22 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_economics', '0002_auto_20180108_1433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qualityoflife',
            options={'permissions': (('restrict_to_national', 'Can only use data from the same location country'), ('restrict_to_local', 'Can only use data from a specific location')), 'verbose_name': 'QLm1 Quality of Life record', 'verbose_name_plural': 'QLm2 Quality of Life records'},
        ),
        migrations.AlterModelOptions(
            name='resourcehospitaladmission',
            options={'permissions': (('restrict_to_national', 'Can only use data from the same location country'), ('restrict_to_local', 'Can only use data from a specific location'))},
        ),
        migrations.AlterModelOptions(
            name='resourcelog',
            options={'permissions': (('restrict_to_national', 'Can only use data from the same location country'), ('restrict_to_local', 'Can only use data from a specific location')), 'verbose_name': 'RLm1 Resource Usage Log', 'verbose_name_plural': 'RLm2 Resource Usage Logs'},
        ),
        migrations.AlterModelOptions(
            name='resourcerehabilitation',
            options={'permissions': (('restrict_to_national', 'Can only use data from the same location country'), ('restrict_to_local', 'Can only use data from a specific location'))},
        ),
        migrations.AlterModelOptions(
            name='resourcevisit',
            options={'permissions': (('restrict_to_national', 'Can only use data from the same location country'), ('restrict_to_local', 'Can only use data from a specific location'))},
        ),
    ]
