# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-04 13:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import wp4.compare.validators


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0016_auto_20160504_1343'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health_economics', '0003_auto_20160501_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceHospitalAdmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='RH01 reason')),
                ('had_surgery', models.NullBooleanField(verbose_name='RH02 had surgery')),
                ('days_in_itu', models.PositiveSmallIntegerField(default=0, verbose_name='RH03 days in itu')),
                ('days_in_hospital', models.PositiveSmallIntegerField(default=1, verbose_name='RH04 days in hospital')),
                ('created_by', models.ForeignKey(help_text='User account for the person logged in when this record was made/updated', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResourceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('version', models.PositiveIntegerField(default=0, help_text='Internal tracking version number')),
                ('record_locked', models.BooleanField(default=False, help_text='Not presently implemented or used')),
                ('date_given', models.DateField(blank=True, help_text='Date can not be in the future', null=True, validators=[wp4.compare.validators.validate_not_in_future], verbose_name='RL01 date given')),
                ('date_returned', models.DateField(blank=True, help_text='Date can not be in the future', null=True, validators=[wp4.compare.validators.validate_not_in_future], verbose_name='RL02 date returned')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='RL03 notes')),
                ('created_by', models.ForeignKey(help_text='User account for the person logged in when this record was made/updated', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compare.Recipient')),
            ],
            options={
                'verbose_name': 'RLm1 Resource Usage Log',
                'verbose_name_plural': 'RLm2 Resource Usage Logs',
            },
        ),
        migrations.CreateModel(
            name='ResourceRehabilitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='RR01 reason')),
                ('days_in_hospital', models.PositiveSmallIntegerField(default=1, verbose_name='RR02 days in hospital')),
                ('created_by', models.ForeignKey(help_text='User account for the person logged in when this record was made/updated', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health_economics.ResourceLog')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResourceVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'RVc01 appointment at GP'), (2, 'RVc02 GP visited'), (3, 'RVc03 appointment at specialist'), (4, 'RVc04 A&E')], verbose_name='RV01 visit type')),
                ('created_by', models.ForeignKey(help_text='User account for the person logged in when this record was made/updated', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health_economics.ResourceLog')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='resourcehospitaladmission',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health_economics.ResourceLog'),
        ),
    ]
