# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 19:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff_person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffjob',
            name='description',
            field=models.CharField(help_text='Job Label', max_length=100),
        ),
        migrations.AlterField(
            model_name='staffperson',
            name='based_at',
            field=models.ForeignKey(blank=True, help_text='Link to a primary hospital location for the member of staff', null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.Hospital'),
        ),
        migrations.AlterField(
            model_name='staffperson',
            name='created_by',
            field=models.ForeignKey(help_text='User account for the person logged in when this record was made/updated', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='staffperson',
            name='record_locked',
            field=models.BooleanField(default=False, help_text='Not presently implemented or used'),
        ),
        migrations.AlterField(
            model_name='staffperson',
            name='version',
            field=models.PositiveIntegerField(default=0, help_text='Internal tracking version number'),
        ),
    ]
