# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 01:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compare', '0001_initial'),
        ('perfusion_machine', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomisation',
            name='allocated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='RA04 allocated by'),
        ),
        migrations.AddField(
            model_name='randomisation',
            name='donor',
            field=models.OneToOneField(blank=True, default=None, help_text='Internal link to the Donor', null=True, on_delete=django.db.models.deletion.CASCADE, to='compare.Donor'),
        ),
        migrations.AddField(
            model_name='procurementresource',
            name='organ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compare.Organ', verbose_name='PR01 related kidney'),
        ),
        migrations.AddField(
            model_name='organallocation',
            name='organ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compare.Organ'),
        ),
        migrations.AddField(
            model_name='organallocation',
            name='perfusion_technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipient_perfusion_technician_set', to=settings.AUTH_USER_MODEL, verbose_name='OA01 name of transplant technician'),
        ),
        migrations.AddField(
            model_name='organallocation',
            name='reallocation',
            field=models.OneToOneField(blank=True, default=None, help_text='Internal forward link value to another OrganAllocation record', null=True, on_delete=django.db.models.deletion.CASCADE, to='compare.OrganAllocation'),
        ),
        migrations.AddField(
            model_name='organallocation',
            name='theatre_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipient_transplant_coordinator_set', to=settings.AUTH_USER_MODEL, verbose_name='OA04 name of the theatre contact'),
        ),
        migrations.AddField(
            model_name='organallocation',
            name='transplant_hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.Hospital', verbose_name='OA03 transplant hospital'),
        ),
        migrations.AddField(
            model_name='organ',
            name='donor',
            field=models.ForeignKey(help_text='Internal link to the Donor', on_delete=django.db.models.deletion.CASCADE, to='compare.Donor'),
        ),
        migrations.AddField(
            model_name='organ',
            name='perfusion_machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='perfusion_machine.Machine', verbose_name='OR24 perfusion machine'),
        ),
        migrations.AddField(
            model_name='donor',
            name='_left_kidney',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='left_kidney', to='compare.Organ'),
        ),
        migrations.AddField(
            model_name='donor',
            name='_right_kidney',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='right_kidney', to='compare.Organ'),
        ),
        migrations.AddField(
            model_name='donor',
            name='perfusion_technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donor_perfusion_technician_set', to=settings.AUTH_USER_MODEL, verbose_name='DO03 name of transplant technician'),
        ),
        migrations.AddField(
            model_name='donor',
            name='person',
            field=models.OneToOneField(help_text='Internal link to Patient', on_delete=django.db.models.deletion.CASCADE, to='compare.Patient'),
        ),
        migrations.AddField(
            model_name='donor',
            name='retrieval_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compare.RetrievalTeam', verbose_name='DO01 retrieval team'),
        ),
        migrations.AddField(
            model_name='donor',
            name='transplant_coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donor_transplant_coordinator_set', to=settings.AUTH_USER_MODEL, verbose_name='DO04 name of the SN-OD'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='recipient',
            order_with_respect_to='organ',
        ),
        migrations.AlterOrderWithRespectTo(
            name='organallocation',
            order_with_respect_to='organ',
        ),
        migrations.AlterOrderWithRespectTo(
            name='donor',
            order_with_respect_to='retrieval_team',
        ),
    ]
