# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('compare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='retrievalteam',
            name='based_at',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.Hospital', verbose_name='RT02 base hospital'),
        ),
    ]
