# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 15:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0002_auto_20151217_1429'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donor',
            options={'verbose_name': 'DOm1 donor', 'verbose_name_plural': 'DOm2 donors'},
        ),
    ]
