# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 12:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compare', '0002_retrievalteam_based_at'),
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('perfusion_machine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='retrievalteam',
            name='created_by',
            field=models.ForeignKey(help_text='User account for the person logged in when this record was made/updated', on_delete=django.db.models.deletion.CASCADE, related_name='compare_retrievalteam_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipient',
            name='allocation',
            field=models.OneToOneField(help_text='Internal link to OrganAllocation', on_delete=django.db.models.deletion.CASCADE, to='compare.OrganAllocation'),
        ),
        migrations.AddField(
            model_name='recipient',
            name='created_by',
            field=models.ForeignKey(help_text='User account for the person logged in when this record was made/updated', on_delete=django.db.models.deletion.CASCADE, related_name='compare_recipient_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipient',
            name='organ',
            field=models.OneToOneField(help_text='Internal link to Organ', on_delete=django.db.models.deletion.CASCADE, to='compare.Organ'),
        ),
        migrations.AddField(
            model_name='recipient',
            name='person',
            field=models.OneToOneField(help_text='Internal link to OrganPerson', on_delete=django.db.models.deletion.CASCADE, to='compare.OrganPerson'),
        ),
        migrations.AddField(
            model_name='randomisation',
            name='donor',
            field=models.OneToOneField(blank=True, default=None, help_text='Internal link to the Donor', null=True, on_delete=django.db.models.deletion.CASCADE, to='compare.Donor'),
        ),
        migrations.AddField(
            model_name='procurementresource',
            name='created_by',
            field=models.ForeignKey(help_text='User account for the person logged in when this record was made/updated', on_delete=django.db.models.deletion.CASCADE, related_name='compare_procurementresource_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procurementresource',
            name='organ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compare.Organ', verbose_name='PR01 related kidney'),
        ),
        migrations.AddField(
            model_name='organperson',
            name='created_by',
            field=models.ForeignKey(help_text='User account for the person logged in when this record was made/updated', on_delete=django.db.models.deletion.CASCADE, related_name='compare_organperson_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organallocation',
            name='created_by',
            field=models.ForeignKey(help_text='User account for the person logged in when this record was made/updated', on_delete=django.db.models.deletion.CASCADE, related_name='compare_organallocation_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organallocation',
            name='organ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compare.Organ'),
        ),
        migrations.AddField(
            model_name='organallocation',
            name='perfusion_technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipient_perfusion_technician_set', to=settings.AUTH_USER_MODEL, verbose_name='OA01 name of transplant technician'),
        ),
        migrations.AddField(
            model_name='organallocation',
            name='reallocation',
            field=models.OneToOneField(blank=True, default=None, help_text='Internal forward link value to another OrganAllocation record', null=True, on_delete=django.db.models.deletion.CASCADE, to='compare.OrganAllocation'),
        ),
        migrations.AddField(
            model_name='organallocation',
            name='theatre_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipient_transplant_coordinator_set', to=settings.AUTH_USER_MODEL, verbose_name='OA04 name of the theatre contact'),
        ),
        migrations.AddField(
            model_name='organallocation',
            name='transplant_hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.Hospital', verbose_name='OA03 transplant hospital'),
        ),
        migrations.AddField(
            model_name='organ',
            name='created_by',
            field=models.ForeignKey(help_text='User account for the person logged in when this record was made/updated', on_delete=django.db.models.deletion.CASCADE, related_name='compare_organ_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organ',
            name='donor',
            field=models.ForeignKey(help_text='Internal link to the Donor', on_delete=django.db.models.deletion.CASCADE, to='compare.Donor'),
        ),
        migrations.AddField(
            model_name='organ',
            name='perfusion_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='perfusion_machine.PerfusionFile', verbose_name='OR25 machine file'),
        ),
        migrations.AddField(
            model_name='organ',
            name='perfusion_machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='perfusion_machine.PerfusionMachine', verbose_name='OR24 perfusion machine'),
        ),
        migrations.AddField(
            model_name='donor',
            name='_left_kidney',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='left_kidney', to='compare.Organ'),
        ),
        migrations.AddField(
            model_name='donor',
            name='_right_kidney',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='right_kidney', to='compare.Organ'),
        ),
        migrations.AddField(
            model_name='donor',
            name='created_by',
            field=models.ForeignKey(help_text='User account for the person logged in when this record was made/updated', on_delete=django.db.models.deletion.CASCADE, related_name='compare_donor_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donor',
            name='perfusion_technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donor_perfusion_technician_set', to=settings.AUTH_USER_MODEL, verbose_name='DO03 name of transplant technician'),
        ),
        migrations.AddField(
            model_name='donor',
            name='person',
            field=models.OneToOneField(help_text='Internal link to OrganPerson', on_delete=django.db.models.deletion.CASCADE, to='compare.OrganPerson'),
        ),
        migrations.AddField(
            model_name='donor',
            name='retrieval_hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.Hospital', verbose_name='DO06 donor hospital'),
        ),
        migrations.AddField(
            model_name='donor',
            name='retrieval_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compare.RetrievalTeam', verbose_name='DO01 retrieval team'),
        ),
        migrations.AddField(
            model_name='donor',
            name='transplant_coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donor_transplant_coordinator_set', to=settings.AUTH_USER_MODEL, verbose_name='DO04 name of the SN-OD'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='recipient',
            order_with_respect_to='organ',
        ),
        migrations.AlterOrderWithRespectTo(
            name='organallocation',
            order_with_respect_to='organ',
        ),
        migrations.AlterOrderWithRespectTo(
            name='donor',
            order_with_respect_to='retrieval_team',
        ),
    ]
