# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0002_auto_20170317_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organ',
            name='not_allocated_reason',
            field=models.CharField(blank=True, max_length=250, verbose_name='OR31 not allocated because'),
        ),
        migrations.AlterField(
            model_name='randomisation',
            name='allocated_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='RA03 allocated on'),
        ),
    ]
