# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0003_auto_20170215_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='trial_id',
            field=models.CharField(blank=True, max_length=10, verbose_name='DO99 donor id'),
        ),
        migrations.AddField(
            model_name='organ',
            name='trial_id',
            field=models.CharField(blank=True, max_length=10, verbose_name='OR99 organ id'),
        ),
    ]
