# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0003_auto_20160106_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='admin_notes',
            field=models.TextField(blank=True, verbose_name='DO50 Admin notes'),
        ),
        migrations.AddField(
            model_name='organ',
            name='admin_notes',
            field=models.TextField(blank=True, verbose_name='DO50 Admin notes'),
        ),
    ]
