# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-14 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0004_auto_20160108_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='randomisation',
            name='country',
        ),
        migrations.AddField(
            model_name='randomisation',
            name='list_code',
            field=models.PositiveSmallIntegerField(choices=[(1, 'RNc01 UK Live list'), (2, 'RNc02 Europe Live list'), (4, 'RNc03 UK Offline list'), (3, 'RNc04 Europe Offline list')], default=1, verbose_name='RA01 list code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='randomisation',
            name='allocated_on',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='RA03 allocated on'),
        ),
    ]
