# Generated by Django 2.0.1 on 2018-01-08 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0004_auto_20170609_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='organ',
            name='paper_form_was_the_source',
            field=models.NullBooleanField(verbose_name='OR97 Was this data entered from a paper record'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='_left_kidney',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='left_kidney', to='compare.Organ'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='_right_kidney',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='right_kidney', to='compare.Organ'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='perfusion_technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donor_perfusion_technician_set', to=settings.AUTH_USER_MODEL, verbose_name='DO03 name of transplant technician'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='person',
            field=models.OneToOneField(help_text='Internal link to Patient', on_delete=django.db.models.deletion.PROTECT, to='compare.Patient'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='retrieval_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compare.RetrievalTeam', verbose_name='DO01 retrieval team'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='transplant_coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='donor_transplant_coordinator_set', to=settings.AUTH_USER_MODEL, verbose_name='DO04 name of the SN-OD'),
        ),
        migrations.AlterField(
            model_name='organ',
            name='donor',
            field=models.ForeignKey(help_text='Internal link to the Donor', on_delete=django.db.models.deletion.PROTECT, to='compare.Donor'),
        ),
        migrations.AlterField(
            model_name='organ',
            name='perfusion_machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='perfusion_machine.Machine', verbose_name='OR24 perfusion machine'),
        ),
        migrations.AlterField(
            model_name='organ',
            name='trial_id',
            field=models.CharField(blank=True, max_length=10, verbose_name='OR98 organ id'),
        ),
        migrations.AlterField(
            model_name='organallocation',
            name='organ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compare.Organ'),
        ),
        migrations.AlterField(
            model_name='organallocation',
            name='perfusion_technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recipient_perfusion_technician_set', to=settings.AUTH_USER_MODEL, verbose_name='OA01 name of transplant technician'),
        ),
        migrations.AlterField(
            model_name='organallocation',
            name='reallocation',
            field=models.OneToOneField(blank=True, default=None, help_text='Internal forward link value to another OrganAllocation record', null=True, on_delete=django.db.models.deletion.PROTECT, to='compare.OrganAllocation'),
        ),
        migrations.AlterField(
            model_name='organallocation',
            name='theatre_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recipient_transplant_coordinator_set', to=settings.AUTH_USER_MODEL, verbose_name='OA04 name of the theatre contact'),
        ),
        migrations.AlterField(
            model_name='organallocation',
            name='transplant_hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='locations.Hospital', verbose_name='OA03 transplant hospital'),
        ),
        migrations.AlterField(
            model_name='procurementresource',
            name='organ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compare.Organ', verbose_name='PR01 related kidney'),
        ),
        migrations.AlterField(
            model_name='randomisation',
            name='allocated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='RA04 allocated by'),
        ),
        migrations.AlterField(
            model_name='randomisation',
            name='donor',
            field=models.OneToOneField(blank=True, default=None, help_text='Internal link to the Donor', null=True, on_delete=django.db.models.deletion.PROTECT, to='compare.Donor'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='allocation',
            field=models.OneToOneField(help_text='Internal link to OrganAllocation', on_delete=django.db.models.deletion.PROTECT, to='compare.OrganAllocation'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='organ',
            field=models.OneToOneField(help_text='Internal link to Organ', on_delete=django.db.models.deletion.PROTECT, to='compare.Organ'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='person',
            field=models.OneToOneField(help_text='Internal link to Patient', on_delete=django.db.models.deletion.PROTECT, to='compare.Patient'),
        ),
        migrations.AlterField(
            model_name='retrievalteam',
            name='based_at',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.Hospital', verbose_name='RT02 base hospital'),
        ),
    ]
