# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 17:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compare', '0004_auto_20170310_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomisation',
            name='allocated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='RA04 allocated by'),
        ),
    ]
