# Generated by Django 2.0.1 on 2018-01-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0005_auto_20180108_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='organ',
            name='included_for_analysis',
            field=models.BooleanField(default=False, verbose_name='OR96 included for analysis'),
        ),
    ]
