# Generated by Django 2.0.1 on 2018-01-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0006_organ_included_for_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='organ',
            name='excluded_from_analysis_because',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='OR95 excluded from analysis because'),
        ),
    ]
