# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0008_auto_20160122_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='organ',
            name='allocated',
            field=models.BooleanField(default=False, verbose_name='DO51 Has this kidney been allocated?'),
        ),
    ]
