# Generated by Django 2.1.7 on 2019-02-22 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0008_auto_20180403_1023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donor',
            options={'permissions': (('restrict_to_national', 'Can only use data from the same location country'), ('restrict_to_local', 'Can only use data from a specific location')), 'verbose_name': 'DOm1 donor', 'verbose_name_plural': 'DOm2 donors'},
        ),
        migrations.AlterModelOptions(
            name='organ',
            options={'base_manager_name': 'objects', 'default_manager_name': 'objects', 'ordering': ['id'], 'permissions': (('restrict_to_national', 'Can only use data from the same location country'), ('restrict_to_local', 'Can only use data from a specific location')), 'verbose_name': 'ORm1 organ', 'verbose_name_plural': 'ORm2 organs'},
        ),
        migrations.AlterModelOptions(
            name='organallocation',
            options={'get_latest_by': 'pk', 'permissions': (('restrict_to_national', 'Can only use data from the same location country'), ('restrict_to_local', 'Can only use data from a specific location')), 'verbose_name': 'OAm1 organ allocation', 'verbose_name_plural': 'OAm2 organ allocations'},
        ),
        migrations.AlterModelOptions(
            name='procurementresource',
            options={'ordering': ['id'], 'permissions': (), 'verbose_name': 'PRm1 procurement resource', 'verbose_name_plural': 'PRm2 procurement resources'},
        ),
        migrations.AlterModelOptions(
            name='recipient',
            options={'get_latest_by': 'pk', 'permissions': (('restrict_to_national', 'Can only use data from the same location country'), ('restrict_to_local', 'Can only use data from a specific location')), 'verbose_name': 'REm1 recipient', 'verbose_name_plural': 'REm2 recipients'},
        ),
        migrations.AlterModelOptions(
            name='retrievalteam',
            options={'ordering': ['centre_code'], 'permissions': (('restrict_to_national', 'Can only use data from the same location country'), ('restrict_to_local', 'Can only use data from a specific location')), 'verbose_name': 'RTm1 retrieval team', 'verbose_name_plural': 'RTm2 retrieval teams'},
        ),
    ]
