# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-19 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import wp4.compare.validators


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0011_auto_20160212_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='death_diagnosed',
            field=models.DateTimeField(blank=True, help_text='DO43h This also counts as Date of Death for donor', null=True, validators=[wp4.compare.validators.validate_between_1900_2050, wp4.compare.validators.validate_not_in_future], verbose_name='DO43 knife to skin time'),
        ),
    ]
