# Generated by Django 2.2.2 on 2019-06-17 16:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0012_auto_20190503_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='panel_reactive_antibodies',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='panel_reactive_antibodies_unknown',
        ),
        migrations.AddField(
            model_name='recipient',
            name='panel_reactive_antibodies',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='RE99 panel reactive antibodies'),
        ),
        migrations.AddField(
            model_name='recipient',
            name='panel_reactive_antibodies_unknown',
            field=models.BooleanField(default=False, help_text='Internal unknown flag'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='record_locked',
            field=models.BooleanField(default=False, help_text='Locked by the admin team. This can only be reversed by the System Administrator'),
        ),
        migrations.AlterField(
            model_name='organ',
            name='record_locked',
            field=models.BooleanField(default=False, help_text='Locked by the admin team. This can only be reversed by the System Administrator'),
        ),
        migrations.AlterField(
            model_name='organallocation',
            name='record_locked',
            field=models.BooleanField(default=False, help_text='Locked by the admin team. This can only be reversed by the System Administrator'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='record_locked',
            field=models.BooleanField(default=False, help_text='Locked by the admin team. This can only be reversed by the System Administrator'),
        ),
        migrations.AlterField(
            model_name='procurementresource',
            name='record_locked',
            field=models.BooleanField(default=False, help_text='Locked by the admin team. This can only be reversed by the System Administrator'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='record_locked',
            field=models.BooleanField(default=False, help_text='Locked by the admin team. This can only be reversed by the System Administrator'),
        ),
    ]
