# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import wp4.compare.validators


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0012_auto_20160219_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='organperson',
            name='date_of_death',
            field=models.DateField(blank=True, null=True, validators=[wp4.compare.validators.validate_not_in_future], verbose_name='OP08 date of death'),
        ),
        migrations.AddField(
            model_name='organperson',
            name='date_of_death_unknown',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='organ',
            name='transplantable',
            field=models.NullBooleanField(help_text='OR07h This answer can be amended after randomisation and saving of the form if necessary', verbose_name='OR07 is transplantable'),
        ),
    ]
