# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 19:38
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import wp4.compare.validators


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0013_auto_20160226_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='age',
            field=models.PositiveSmallIntegerField(help_text='Age must be in the range 50-99', validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(99)], verbose_name='DO12 age'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='arrival_at_donor_hospital',
            field=models.DateTimeField(blank=True, help_text='Date must be fall within 1900-2050, and not be in the future', null=True, validators=[wp4.compare.validators.validate_between_1900_2050, wp4.compare.validators.validate_not_in_future], verbose_name='DO11 arrival at donor hospital'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='arrival_at_donor_hospital_unknown',
            field=models.BooleanField(default=False, help_text='Internal unknown flag'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='call_received',
            field=models.DateTimeField(blank=True, help_text='Date must be fall within 1900-2050, and not be in the future', null=True, validators=[wp4.compare.validators.validate_between_1900_2050, wp4.compare.validators.validate_not_in_future], verbose_name='DO05 Consultant to MTO called at'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='call_received_unknown',
            field=models.BooleanField(default=False, help_text='Internal unknown flag'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='circulatory_arrest',
            field=models.DateTimeField(blank=True, help_text='Date must be fall within 1900-2050, and not be in the future', null=True, validators=[wp4.compare.validators.validate_between_1900_2050, wp4.compare.validators.validate_not_in_future], verbose_name='DO41 end of cardiac output'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='circulatory_arrest_unknown',
            field=models.BooleanField(default=False, help_text='Internal unknown flag'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='created_by',
            field=models.ForeignKey(help_text='User account for the person logged in when this record was made/updated', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donor',
            name='date_admitted_to_itu',
            field=models.DateField(blank=True, help_text='Date must be fall within 1900-2050, and not be in the future', null=True, validators=[wp4.compare.validators.validate_between_1900_2050, wp4.compare.validators.validate_not_in_future], verbose_name='DO15 when admitted to ITU'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='date_admitted_to_itu_unknown',
            field=models.BooleanField(default=False, help_text='Internal unknown flag'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='date_of_admission',
            field=models.DateField(blank=True, help_text='Date must be fall within 1900-2050, and not be in the future', null=True, validators=[wp4.compare.validators.validate_between_1900_2050, wp4.compare.validators.validate_not_in_future], verbose_name='DO13 date of admission'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='date_of_admission_unknown',
            field=models.BooleanField(default=False, help_text='Internal unknown flag'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='date_of_procurement',
            field=models.DateField(blank=True, help_text='Date must be fall within 1900-2050, and not be in the future', null=True, validators=[wp4.compare.validators.validate_between_1900_2050, wp4.compare.validators.validate_not_in_future], verbose_name='DO16 date of procurement'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='death_diagnosed',
            field=models.DateTimeField(blank=True, help_text='DO43h This also counts as Date of Death for donor. Date must be fall within 1900-2050, and not be in the future', null=True, validators=[wp4.compare.validators.validate_between_1900_2050, wp4.compare.validators.validate_not_in_future], verbose_name='DO43 knife to skin time'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='depart_perfusion_centre_unknown',
            field=models.BooleanField(default=False, help_text='Internal unknown flag'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='diastolic_blood_pressure',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Value must be in the range 10-200', null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(200)], verbose_name='DO28 last diastolic blood pressure'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='diuresis_last_day_unknown',
            field=models.BooleanField(default=False, help_text='Internal unknown flag'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='diuresis_last_hour_unknown',
            field=models.BooleanField(default=False, help_text='Internal unknown flag'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='ice_boxes_filled',
            field=models.DateTimeField(blank=True, help_text='Date must be fall within 1900-2050, and not be in the future', null=True, validators=[wp4.compare.validators.validate_between_1900_2050, wp4.compare.validators.validate_not_in_future], verbose_name='DO09 ice boxes filled'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='ice_boxes_filled_unknown',
            field=models.BooleanField(default=False, help_text='Internal unknown flag'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='length_of_no_touch',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Value must be in the range 1-60 minutes', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)], verbose_name='DO42 length of no touch period (minutes)'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='life_support_withdrawal',
            field=models.DateTimeField(blank=True, help_text='Date must be fall within 1900-2050, and not be in the future', null=True, validators=[wp4.compare.validators.validate_between_1900_2050, wp4.compare.validators.validate_not_in_future], verbose_name='DO38 withdrawal of life support'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='o2_saturation',
            field=models.DateTimeField(blank=True, help_text='Date must be fall within 1900-2050, and not be in the future', null=True, validators=[wp4.compare.validators.validate_between_1900_2050, wp4.compare.validators.validate_not_in_future], verbose_name='DO40 O2 saturation below 80%'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='o2_saturation_unknown',
            field=models.BooleanField(default=False, help_text='Internal unknown flag'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='perfusion_started',
            field=models.DateTimeField(blank=True, help_text='Date must be fall within 1900-2050, and not be in the future', null=True, validators=[wp4.compare.validators.validate_between_1900_2050, wp4.compare.validators.validate_not_in_future], verbose_name='DO44 start in-situ cold perfusion'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='perfusion_started_unknown',
            field=models.BooleanField(default=False, help_text='Internal unknown flag'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='person',
            field=models.OneToOneField(help_text='Internal link to OrganPerson', on_delete=django.db.models.deletion.CASCADE, to='compare.OrganPerson'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='procurement_form_completed',
            field=models.BooleanField(default=False, help_text='Internal value to flag when technician thinks the form is complete'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='record_locked',
            field=models.BooleanField(default=False, help_text='Not presently implemented or used'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='scheduled_start',
            field=models.DateTimeField(blank=True, help_text='Date must be fall within 1900-2050', null=True, validators=[wp4.compare.validators.validate_between_1900_2050], verbose_name='DO07 time of withdrawal therapy'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='scheduled_start_unknown',
            field=models.BooleanField(default=False, help_text='Internal unknown flag'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='sequence_number',
            field=models.PositiveSmallIntegerField(default=0, help_text='Internal value for tracking trial ID sequence number. Value of 1-99', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='donor',
            name='systolic_blood_pressure',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Value must be in the range 10-200', null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(200)], verbose_name='DO27 last systolic blood pressure'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='systolic_pressure_low',
            field=models.DateTimeField(blank=True, help_text='Date must be fall within 1900-2050, and not be in the future', null=True, validators=[wp4.compare.validators.validate_between_1900_2050, wp4.compare.validators.validate_not_in_future], verbose_name='DO39 systolic arterial pressure'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='systolic_pressure_low_unknown',
            field=models.BooleanField(default=False, help_text='Internal unknown flag'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='technician_arrival',
            field=models.DateTimeField(blank=True, help_text='Date must be fall within 1900-2050, and not be in the future', null=True, validators=[wp4.compare.validators.validate_between_1900_2050, wp4.compare.validators.validate_not_in_future], verbose_name='DO08 arrival time of technician'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='technician_arrival_unknown',
            field=models.BooleanField(default=False, help_text='Internal unknown flag'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='version',
            field=models.PositiveIntegerField(default=0, help_text='Internal tracking version number'),
        ),
        migrations.AlterField(
            model_name='organ',
            name='created_by',
            field=models.ForeignKey(help_text='User account for the person logged in when this record was made/updated', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organ',
            name='donor',
            field=models.ForeignKey(help_text='Internal link to the Donor', on_delete=django.db.models.deletion.CASCADE, to='compare.Donor'),
        ),
        migrations.AlterField(
            model_name='organ',
            name='ice_container_replenished_at',
            field=models.DateTimeField(blank=True, help_text='Date must be fall within 1900-2050, and not be in the future', null=True, validators=[wp4.compare.validators.validate_between_1900_2050, wp4.compare.validators.validate_not_in_future], verbose_name='OR21 ice container replenished at'),
        ),
        migrations.AlterField(
            model_name='organ',
            name='ice_container_replenished_at_unknown',
            field=models.BooleanField(default=False, help_text='Internal unknown flag'),
        ),
        migrations.AlterField(
            model_name='organ',
            name='oxygen_bottle_changed_at',
            field=models.DateTimeField(blank=True, help_text='Date must be fall within 1900-2050, and not be in the future', null=True, validators=[wp4.compare.validators.validate_between_1900_2050, wp4.compare.validators.validate_not_in_future], verbose_name='OR19 oxygen bottle changed at'),
        ),
        migrations.AlterField(
            model_name='organ',
            name='oxygen_bottle_changed_at_unknown',
            field=models.BooleanField(default=False, help_text='Internal unknown flag'),
        ),
        migrations.AlterField(
            model_name='organ',
            name='perfusion_started',
            field=models.DateTimeField(blank=True, help_text='Date must be fall within 1900-2050, and not be in the future', null=True, validators=[wp4.compare.validators.validate_between_1900_2050, wp4.compare.validators.validate_not_in_future], verbose_name='OR11 machine perfusion'),
        ),
        migrations.AlterField(
            model_name='organ',
            name='record_locked',
            field=models.BooleanField(default=False, help_text='Not presently implemented or used'),
        ),
        migrations.AlterField(
            model_name='organ',
            name='removal',
            field=models.DateTimeField(blank=True, help_text='Date must be fall within 1900-2050, and not be in the future', null=True, validators=[wp4.compare.validators.validate_between_1900_2050, wp4.compare.validators.validate_not_in_future], verbose_name='OR02 time out'),
        ),
        migrations.AlterField(
            model_name='organ',
            name='renal_arteries',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Number of arteries must be in range 0-5', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='OR03 number of renal arteries'),
        ),
        migrations.AlterField(
            model_name='organ',
            name='transplantation_form_completed',
            field=models.BooleanField(default=False, help_text='Internal value to flag when technician thinks the form is complete'),
        ),
        migrations.AlterField(
            model_name='organ',
            name='version',
            field=models.PositiveIntegerField(default=0, help_text='Internal tracking version number'),
        ),
        migrations.AlterField(
            model_name='organallocation',
            name='arrival_at_recipient_hospital',
            field=models.DateTimeField(blank=True, help_text='Date must be fall within 1900-2050, and not be in the future', null=True, validators=[wp4.compare.validators.validate_between_1900_2050, wp4.compare.validators.validate_not_in_future], verbose_name='OA08 arrival at transplant hospital'),
        ),
        migrations.AlterField(
            model_name='organallocation',
            name='arrival_at_recipient_hospital_unknown',
            field=models.BooleanField(default=False, help_text='Internal unknown flag'),
        ),
        migrations.AlterField(
            model_name='organallocation',
            name='call_received',
            field=models.DateTimeField(blank=True, help_text='Date must be fall within 1900-2050, and not be in the future', null=True, validators=[wp4.compare.validators.validate_between_1900_2050, wp4.compare.validators.validate_not_in_future], verbose_name='OA02 call received from transplant co-ordinator at'),
        ),
        migrations.AlterField(
            model_name='organallocation',
            name='call_received_unknown',
            field=models.BooleanField(default=False, help_text='Internal unknown flag'),
        ),
        migrations.AlterField(
            model_name='organallocation',
            name='created_by',
            field=models.ForeignKey(help_text='User account for the person logged in when this record was made/updated', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organallocation',
            name='depart_perfusion_centre',
            field=models.DateTimeField(blank=True, help_text='Date must be fall within 1900-2050, and not be in the future', null=True, validators=[wp4.compare.validators.validate_between_1900_2050, wp4.compare.validators.validate_not_in_future], verbose_name='OA07 departure from hub'),
        ),
        migrations.AlterField(
            model_name='organallocation',
            name='depart_perfusion_centre_unknown',
            field=models.BooleanField(default=False, help_text='Internal unknown flag'),
        ),
        migrations.AlterField(
            model_name='organallocation',
            name='organ',
            field=models.ForeignKey(help_text='Internal link to the Organ', on_delete=django.db.models.deletion.CASCADE, to='compare.Organ'),
        ),
        migrations.AlterField(
            model_name='organallocation',
            name='reallocation',
            field=models.OneToOneField(blank=True, default=None, help_text='Internal forward link value to another OrganAllocation record', null=True, on_delete=django.db.models.deletion.CASCADE, to='compare.OrganAllocation'),
        ),
        migrations.AlterField(
            model_name='organallocation',
            name='record_locked',
            field=models.BooleanField(default=False, help_text='Not presently implemented or used'),
        ),
        migrations.AlterField(
            model_name='organallocation',
            name='scheduled_start',
            field=models.DateTimeField(blank=True, help_text='Date must be fall within 1900-2050', null=True, validators=[wp4.compare.validators.validate_between_1900_2050], verbose_name='OA05 scheduled start'),
        ),
        migrations.AlterField(
            model_name='organallocation',
            name='scheduled_start_unknown',
            field=models.BooleanField(default=False, help_text='Internal unknown flag'),
        ),
        migrations.AlterField(
            model_name='organallocation',
            name='technician_arrival',
            field=models.DateTimeField(blank=True, help_text='Date must be fall within 1900-2050, and not be in the future', null=True, validators=[wp4.compare.validators.validate_between_1900_2050, wp4.compare.validators.validate_not_in_future], verbose_name='OA06 arrival time at hub'),
        ),
        migrations.AlterField(
            model_name='organallocation',
            name='technician_arrival_unknown',
            field=models.BooleanField(default=False, help_text='Internal unknown flag'),
        ),
        migrations.AlterField(
            model_name='organallocation',
            name='version',
            field=models.PositiveIntegerField(default=0, help_text='Internal tracking version number'),
        ),
        migrations.AlterField(
            model_name='organperson',
            name='created_by',
            field=models.ForeignKey(help_text='User account for the person logged in when this record was made/updated', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organperson',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Date can not be in the future', null=True, validators=[wp4.compare.validators.validate_not_in_future], verbose_name='OP02 date of birth'),
        ),
        migrations.AlterField(
            model_name='organperson',
            name='date_of_birth_unknown',
            field=models.BooleanField(default=False, help_text='Internal unknown flag'),
        ),
        migrations.AlterField(
            model_name='organperson',
            name='date_of_death',
            field=models.DateField(blank=True, help_text='Date can not be in the future', null=True, validators=[wp4.compare.validators.validate_not_in_future], verbose_name='OP08 date of death'),
        ),
        migrations.AlterField(
            model_name='organperson',
            name='date_of_death_unknown',
            field=models.BooleanField(default=False, help_text='Internal unknown flag'),
        ),
        migrations.AlterField(
            model_name='organperson',
            name='height',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Answer must be in range 100-250cm', null=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(250)], verbose_name='OP05 Height (cm)'),
        ),
        migrations.AlterField(
            model_name='organperson',
            name='record_locked',
            field=models.BooleanField(default=False, help_text='Not presently implemented or used'),
        ),
        migrations.AlterField(
            model_name='organperson',
            name='version',
            field=models.PositiveIntegerField(default=0, help_text='Internal tracking version number'),
        ),
        migrations.AlterField(
            model_name='organperson',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Answer must be in range 20.0-200.0kg', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(20.0), django.core.validators.MaxValueValidator(200.0)], verbose_name='OP04 Weight (kg)'),
        ),
        migrations.AlterField(
            model_name='procurementresource',
            name='created_by',
            field=models.ForeignKey(help_text='Internal User link', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='procurementresource',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Internal value'),
        ),
        migrations.AlterField(
            model_name='procurementresource',
            name='expiry_date_unknown',
            field=models.BooleanField(default=False, help_text='Internal unknown flag'),
        ),
        migrations.AlterField(
            model_name='randomisation',
            name='donor',
            field=models.OneToOneField(blank=True, default=None, help_text='Internal link to the Donor', null=True, on_delete=django.db.models.deletion.CASCADE, to='compare.Donor'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='allocation',
            field=models.OneToOneField(help_text='Internal link to OrganAllocation', on_delete=django.db.models.deletion.CASCADE, to='compare.OrganAllocation'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='anastomosis_started_at',
            field=models.DateTimeField(blank=True, help_text='Date must be fall within 1900-2050, and not be in the future', null=True, validators=[wp4.compare.validators.validate_between_1900_2050, wp4.compare.validators.validate_not_in_future], verbose_name='RE34 start anastomosis at'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='anastomosis_started_at_unknown',
            field=models.BooleanField(default=False, help_text='Internal unknown flag'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='anesthesia_started_at',
            field=models.DateTimeField(blank=True, help_text='Date must be fall within 1900-2050, and not be in the future', null=True, validators=[wp4.compare.validators.validate_between_1900_2050, wp4.compare.validators.validate_not_in_future], verbose_name='RE27 start anesthesia at'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='created_by',
            field=models.ForeignKey(help_text='User account for the person logged in when this record was made/updated', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='knife_to_skin',
            field=models.DateTimeField(blank=True, help_text='Date must be fall within 1900-2050, and not be in the future', null=True, validators=[wp4.compare.validators.validate_between_1900_2050, wp4.compare.validators.validate_not_in_future], verbose_name='RE18 knife to skin time'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='operation_concluded_at',
            field=models.DateTimeField(blank=True, help_text='Date must be fall within 1900-2050, and not be in the future', null=True, validators=[wp4.compare.validators.validate_between_1900_2050, wp4.compare.validators.validate_not_in_future], verbose_name='RE43 operation concluded at'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='organ',
            field=models.OneToOneField(help_text='Internal link to Organ', on_delete=django.db.models.deletion.CASCADE, to='compare.Organ'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='organ_untransplantable',
            field=models.NullBooleanField(help_text='REh25 Either answer means further questions will open below', verbose_name='RE25 kidney discarded'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='perfusion_stopped',
            field=models.DateTimeField(blank=True, help_text='Date must be fall within 1900-2050, and not be in the future', null=True, validators=[wp4.compare.validators.validate_between_1900_2050, wp4.compare.validators.validate_not_in_future], verbose_name='RE20 stop machine perfusion'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='person',
            field=models.OneToOneField(help_text='Internal link to OrganPerson', on_delete=django.db.models.deletion.CASCADE, to='compare.OrganPerson'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='record_locked',
            field=models.BooleanField(default=False, help_text='Not presently implemented or used'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='removed_from_machine_at',
            field=models.DateTimeField(blank=True, help_text='Date must be fall within 1900-2050, and not be in the future', null=True, validators=[wp4.compare.validators.validate_between_1900_2050, wp4.compare.validators.validate_not_in_future], verbose_name='RE23 kidney removed from machine at'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='reperfusion_started_at',
            field=models.DateTimeField(blank=True, help_text='Date must be fall within 1900-2050, and not be in the future', null=True, validators=[wp4.compare.validators.validate_between_1900_2050, wp4.compare.validators.validate_not_in_future], verbose_name='RE35 start reperfusion at'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='reperfusion_started_at_unknown',
            field=models.BooleanField(default=False, help_text='Internal unknown flag'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='systolic_blood_pressure',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Value must be in range 10-200', null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(200)], verbose_name='RE39 systolic blood pressure at reperfusion'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='version',
            field=models.PositiveIntegerField(default=0, help_text='Internal tracking version number'),
        ),
        migrations.AlterField(
            model_name='retrievalteam',
            name='centre_code',
            field=models.PositiveSmallIntegerField(help_text='Value must be in the range 10-99', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(99)], verbose_name='RT01 centre code'),
        ),
        migrations.AlterField(
            model_name='retrievalteam',
            name='created_by',
            field=models.ForeignKey(help_text='Internal tracking', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='retrievalteam',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Internal tracking'),
        ),
    ]
