# Generated by Django 2.2.2 on 2019-06-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0013_auto_20190617_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='record_locked',
            field=models.BooleanField(default=False, help_text='Locked by the admin team. This can only be reversed by the System Administrator', verbose_name='ACM01 Record Locked'),
        ),
        migrations.AlterField(
            model_name='organ',
            name='record_locked',
            field=models.BooleanField(default=False, help_text='Locked by the admin team. This can only be reversed by the System Administrator', verbose_name='ACM01 Record Locked'),
        ),
        migrations.AlterField(
            model_name='organallocation',
            name='record_locked',
            field=models.BooleanField(default=False, help_text='Locked by the admin team. This can only be reversed by the System Administrator', verbose_name='ACM01 Record Locked'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='record_locked',
            field=models.BooleanField(default=False, help_text='Locked by the admin team. This can only be reversed by the System Administrator', verbose_name='ACM01 Record Locked'),
        ),
        migrations.AlterField(
            model_name='procurementresource',
            name='record_locked',
            field=models.BooleanField(default=False, help_text='Locked by the admin team. This can only be reversed by the System Administrator', verbose_name='ACM01 Record Locked'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='record_locked',
            field=models.BooleanField(default=False, help_text='Locked by the admin team. This can only be reversed by the System Administrator', verbose_name='ACM01 Record Locked'),
        ),
    ]
