# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 20:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0014_auto_20160427_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='procurement_form_completed',
            field=models.BooleanField(default=False, help_text='Select Yes when you believe the form is complete and you have no more data to enter', verbose_name='DO99 Form complete'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='sequence_number',
            field=models.PositiveSmallIntegerField(default=0, help_text='Internal value for tracking trial ID sequence number. Value of 1-99', validators=[django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='organ',
            name='admin_notes',
            field=models.TextField(blank=True, verbose_name='OR50 Admin notes'),
        ),
        migrations.AlterField(
            model_name='organ',
            name='transplantation_form_completed',
            field=models.BooleanField(default=False, help_text='Select Yes when you believe the form is complete and you have no more data to enter', verbose_name='OR99 Form complete'),
        ),
        migrations.AlterField(
            model_name='organ',
            name='transplantation_notes',
            field=models.TextField(blank=True, verbose_name='OR51 Transplantation notes'),
        ),
        migrations.AlterField(
            model_name='organallocation',
            name='organ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compare.Organ'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='tape_broken',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2, 'MMc03 Unknown'), (0, 'MMc01 No'), (1, 'MMc02 Yes')], null=True, verbose_name='RE22 tape over regulator broken'),
        ),
    ]
