# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import livefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('version', models.PositiveIntegerField(default=0, help_text='Internal tracking version number')),
                ('record_locked', models.BooleanField(default=False, help_text='Not presently implemented or used')),
                ('live', livefield.fields.LiveField(default=True)),
                ('barcode', models.CharField(blank=True, max_length=20, verbose_name='BC01 barcode number')),
                ('collected', models.NullBooleanField(verbose_name='DM01 sample collected?')),
                ('notes', models.TextField(blank=True, help_text='Deviation record', verbose_name='DM02 notes')),
                ('blood_type', models.PositiveSmallIntegerField(choices=[(1, 'BSc01 Blood SST'), (2, 'BSc02 Blood EDSA')], verbose_name='BS02 blood sample type')),
                ('centrifuged_at', models.DateTimeField(blank=True, null=True, verbose_name='BS01 centrifuged at')),
            ],
            options={
                'verbose_name': 'BSm1 blood sample',
                'abstract': False,
                'ordering': ['person', 'event__taken_at'],
                'permissions': (('view', 'Can view the data, but not modify it'), ('restrict_to_national', 'Can only use data from the same location country'), ('restrict_to_local', 'Can only use data from a specific location')),
                'verbose_name_plural': 'BSm2 blood samples',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('version', models.PositiveIntegerField(default=0, help_text='Internal tracking version number')),
                ('record_locked', models.BooleanField(default=False, help_text='Not presently implemented or used')),
                ('live', livefield.fields.LiveField(default=True)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'EVc01 Blood'), (2, 'EVc02 Urine'), (3, 'EVc03 Perfusate'), (4, 'EVc04 Tissue')], verbose_name='EV01 sample type')),
                ('name', models.PositiveSmallIntegerField(choices=[(1, 'EVc05 donor blood 1'), (2, 'EVc06 donor urine 1'), (3, 'EVc07 donor urine 2'), (4, 'EVc08 organ perfusate 1'), (5, 'EVc09 organ perfusate 2'), (6, 'EVc10 organ perfusate 3'), (7, 'EVc11 organ tissue 1'), (8, 'EVc12 recipient blood 1'), (9, 'EVc13 recipient blood 2')], verbose_name='EV03 sample process name')),
                ('taken_at', models.DateTimeField(blank=True, null=True, verbose_name='EV02 date and time taken')),
            ],
            options={
                'verbose_name': 'EVm1 sample event',
                'abstract': False,
                'ordering': ['type', 'name'],
                'permissions': (('view', 'Can view the data, but not modify it'), ('restrict_to_national', 'Can only use data from the same location country'), ('restrict_to_local', 'Can only use data from a specific location')),
                'verbose_name_plural': 'EVm2 sample events',
            },
        ),
        migrations.CreateModel(
            name='PerfusateSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('version', models.PositiveIntegerField(default=0, help_text='Internal tracking version number')),
                ('record_locked', models.BooleanField(default=False, help_text='Not presently implemented or used')),
                ('live', livefield.fields.LiveField(default=True)),
                ('barcode', models.CharField(blank=True, max_length=20, verbose_name='BC01 barcode number')),
                ('collected', models.NullBooleanField(verbose_name='DM01 sample collected?')),
                ('notes', models.TextField(blank=True, help_text='Deviation record', verbose_name='DM02 notes')),
                ('centrifuged_at', models.DateTimeField(blank=True, null=True, verbose_name='PS01 centrifuged at')),
            ],
            options={
                'verbose_name': 'PSm1 perfusate sample',
                'abstract': False,
                'ordering': ['organ', 'event__taken_at'],
                'permissions': (('view', 'Can view the data, but not modify it'), ('restrict_to_national', 'Can only use data from the same location country'), ('restrict_to_local', 'Can only use data from a specific location')),
                'verbose_name_plural': 'PSm2 perfusate samples',
            },
        ),
        migrations.CreateModel(
            name='TissueSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('version', models.PositiveIntegerField(default=0, help_text='Internal tracking version number')),
                ('record_locked', models.BooleanField(default=False, help_text='Not presently implemented or used')),
                ('live', livefield.fields.LiveField(default=True)),
                ('barcode', models.CharField(blank=True, max_length=20, verbose_name='BC01 barcode number')),
                ('collected', models.NullBooleanField(verbose_name='DM01 sample collected?')),
                ('notes', models.TextField(blank=True, help_text='Deviation record', verbose_name='DM02 notes')),
                ('tissue_type', models.CharField(choices=[('F', 'TSc01 ReK1F'), ('R', 'TSc02 ReK1R')], max_length=1, verbose_name='TS02 tissue sample type')),
            ],
            options={
                'verbose_name': 'TSm1 tissue sample',
                'abstract': False,
                'ordering': ['organ', 'event__taken_at'],
                'permissions': (('view', 'Can view the data, but not modify it'), ('restrict_to_national', 'Can only use data from the same location country'), ('restrict_to_local', 'Can only use data from a specific location')),
                'verbose_name_plural': 'TSm2 tissue samples',
            },
        ),
        migrations.CreateModel(
            name='UrineSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('version', models.PositiveIntegerField(default=0, help_text='Internal tracking version number')),
                ('record_locked', models.BooleanField(default=False, help_text='Not presently implemented or used')),
                ('live', livefield.fields.LiveField(default=True)),
                ('barcode', models.CharField(blank=True, max_length=20, verbose_name='BC01 barcode number')),
                ('collected', models.NullBooleanField(verbose_name='DM01 sample collected?')),
                ('notes', models.TextField(blank=True, help_text='Deviation record', verbose_name='DM02 notes')),
                ('centrifuged_at', models.DateTimeField(blank=True, null=True, verbose_name='US01 centrifuged at')),
            ],
            options={
                'verbose_name': 'USm1 urine sample',
                'abstract': False,
                'ordering': ['person', 'event__taken_at'],
                'permissions': (('view', 'Can view the data, but not modify it'), ('restrict_to_national', 'Can only use data from the same location country'), ('restrict_to_local', 'Can only use data from a specific location')),
                'verbose_name_plural': 'USm2 urine samples',
            },
        ),
    ]
