# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 01:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import livefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compare', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_locked', models.BooleanField(default=False, help_text='locked by the admin team')),
                ('live', livefield.fields.LiveField(default=True)),
                ('barcode', models.CharField(blank=True, max_length=20, verbose_name='BC01 barcode number')),
                ('collected', models.NullBooleanField(verbose_name='DM01 sample collected?')),
                ('notes', models.TextField(blank=True, help_text='Deviation record', verbose_name='DM02 notes')),
                ('blood_type', models.PositiveSmallIntegerField(choices=[(1, 'BSc01 Blood SST'), (2, 'BSc02 Blood EDSA')], verbose_name='BS02 blood sample type')),
                ('centrifuged_at', models.DateTimeField(blank=True, null=True, verbose_name='BS01 centrifuged at')),
            ],
            options={
                'verbose_name': 'BSm1 blood sample',
                'verbose_name_plural': 'BSm2 blood samples',
                'ordering': ['person', 'event__taken_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_locked', models.BooleanField(default=False, help_text='locked by the admin team')),
                ('live', livefield.fields.LiveField(default=True)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'EVc01 Blood'), (2, 'EVc02 Urine'), (3, 'EVc03 Perfusate'), (4, 'EVc04 Tissue')], verbose_name='EV01 sample type')),
                ('name', models.PositiveSmallIntegerField(choices=[(1, 'EVc05 donor blood 1'), (2, 'EVc06 donor urine 1'), (3, 'EVc07 donor urine 2'), (4, 'EVc08 organ perfusate 1'), (5, 'EVc09 organ perfusate 2'), (6, 'EVc10 organ perfusate 3'), (7, 'EVc11 organ tissue 1'), (8, 'EVc12 recipient blood 1'), (9, 'EVc13 recipient blood 2')], verbose_name='EV03 sample process name')),
                ('taken_at', models.DateTimeField(blank=True, null=True, verbose_name='EV02 date and time taken')),
            ],
            options={
                'verbose_name': 'EVm1 sample event',
                'verbose_name_plural': 'EVm2 sample events',
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PerfusateSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_locked', models.BooleanField(default=False, help_text='locked by the admin team')),
                ('live', livefield.fields.LiveField(default=True)),
                ('barcode', models.CharField(blank=True, max_length=20, verbose_name='BC01 barcode number')),
                ('collected', models.NullBooleanField(verbose_name='DM01 sample collected?')),
                ('notes', models.TextField(blank=True, help_text='Deviation record', verbose_name='DM02 notes')),
                ('centrifuged_at', models.DateTimeField(blank=True, null=True, verbose_name='PS01 centrifuged at')),
                ('event', models.ForeignKey(help_text='Link to an event of type Perfusate', on_delete=django.db.models.deletion.CASCADE, to='samples.Event')),
                ('organ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compare.Organ', verbose_name='PS02 sample from')),
            ],
            options={
                'verbose_name': 'PSm1 perfusate sample',
                'verbose_name_plural': 'PSm2 perfusate samples',
                'ordering': ['organ', 'event__taken_at'],
            },
        ),
        migrations.CreateModel(
            name='TissueSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_locked', models.BooleanField(default=False, help_text='locked by the admin team')),
                ('live', livefield.fields.LiveField(default=True)),
                ('barcode', models.CharField(blank=True, max_length=20, verbose_name='BC01 barcode number')),
                ('collected', models.NullBooleanField(verbose_name='DM01 sample collected?')),
                ('notes', models.TextField(blank=True, help_text='Deviation record', verbose_name='DM02 notes')),
                ('tissue_type', models.CharField(choices=[('F', 'TSc01 ReK1F'), ('R', 'TSc02 ReK1R')], max_length=1, verbose_name='TS02 tissue sample type')),
                ('event', models.ForeignKey(help_text='Link to an event of type Tissue', on_delete=django.db.models.deletion.CASCADE, to='samples.Event')),
                ('organ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compare.Organ', verbose_name='TS01 sample from')),
            ],
            options={
                'verbose_name': 'TSm1 tissue sample',
                'verbose_name_plural': 'TSm2 tissue samples',
                'ordering': ['organ', 'event__taken_at'],
            },
        ),
        migrations.CreateModel(
            name='UrineSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_locked', models.BooleanField(default=False, help_text='locked by the admin team')),
                ('live', livefield.fields.LiveField(default=True)),
                ('barcode', models.CharField(blank=True, max_length=20, verbose_name='BC01 barcode number')),
                ('collected', models.NullBooleanField(verbose_name='DM01 sample collected?')),
                ('notes', models.TextField(blank=True, help_text='Deviation record', verbose_name='DM02 notes')),
                ('centrifuged_at', models.DateTimeField(blank=True, null=True, verbose_name='US01 centrifuged at')),
                ('event', models.ForeignKey(help_text='Link to an event of type Urine', on_delete=django.db.models.deletion.CASCADE, to='samples.Event')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compare.Patient', verbose_name='US02 sample from')),
            ],
            options={
                'verbose_name': 'USm1 urine sample',
                'verbose_name_plural': 'USm2 urine samples',
                'ordering': ['person', 'event__taken_at'],
            },
        ),
        migrations.AddField(
            model_name='bloodsample',
            name='event',
            field=models.ForeignKey(help_text='Link to an event of type Blood', on_delete=django.db.models.deletion.CASCADE, to='samples.Event'),
        ),
        migrations.AddField(
            model_name='bloodsample',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compare.Patient', verbose_name='BS03 sample from'),
        ),
    ]
