# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 19:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodsample',
            name='created_by',
            field=models.ForeignKey(help_text='User account for the person logged in when this record was made/updated', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bloodsample',
            name='event',
            field=models.ForeignKey(help_text='Link to an event of type Blood', on_delete=django.db.models.deletion.CASCADE, to='samples.Event'),
        ),
        migrations.AlterField(
            model_name='bloodsample',
            name='notes',
            field=models.TextField(blank=True, help_text='Deviation record', verbose_name='DM02 notes'),
        ),
        migrations.AlterField(
            model_name='bloodsample',
            name='record_locked',
            field=models.BooleanField(default=False, help_text='Not presently implemented or used'),
        ),
        migrations.AlterField(
            model_name='bloodsample',
            name='version',
            field=models.PositiveIntegerField(default=0, help_text='Internal tracking version number'),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(help_text='User account for the person logged in when this record was made/updated', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='record_locked',
            field=models.BooleanField(default=False, help_text='Not presently implemented or used'),
        ),
        migrations.AlterField(
            model_name='event',
            name='version',
            field=models.PositiveIntegerField(default=0, help_text='Internal tracking version number'),
        ),
        migrations.AlterField(
            model_name='event',
            name='worksheet',
            field=models.ForeignKey(help_text='Internal link to the Worksheet', on_delete=django.db.models.deletion.CASCADE, to='samples.Worksheet'),
        ),
        migrations.AlterField(
            model_name='perfusatesample',
            name='created_by',
            field=models.ForeignKey(help_text='User account for the person logged in when this record was made/updated', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='perfusatesample',
            name='event',
            field=models.ForeignKey(help_text='Link to an event of type Perfusate', on_delete=django.db.models.deletion.CASCADE, to='samples.Event'),
        ),
        migrations.AlterField(
            model_name='perfusatesample',
            name='notes',
            field=models.TextField(blank=True, help_text='Deviation record', verbose_name='DM02 notes'),
        ),
        migrations.AlterField(
            model_name='perfusatesample',
            name='record_locked',
            field=models.BooleanField(default=False, help_text='Not presently implemented or used'),
        ),
        migrations.AlterField(
            model_name='perfusatesample',
            name='version',
            field=models.PositiveIntegerField(default=0, help_text='Internal tracking version number'),
        ),
        migrations.AlterField(
            model_name='tissuesample',
            name='created_by',
            field=models.ForeignKey(help_text='User account for the person logged in when this record was made/updated', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tissuesample',
            name='event',
            field=models.ForeignKey(help_text='Link to an event of type Tissue', on_delete=django.db.models.deletion.CASCADE, to='samples.Event'),
        ),
        migrations.AlterField(
            model_name='tissuesample',
            name='notes',
            field=models.TextField(blank=True, help_text='Deviation record', verbose_name='DM02 notes'),
        ),
        migrations.AlterField(
            model_name='tissuesample',
            name='record_locked',
            field=models.BooleanField(default=False, help_text='Not presently implemented or used'),
        ),
        migrations.AlterField(
            model_name='tissuesample',
            name='version',
            field=models.PositiveIntegerField(default=0, help_text='Internal tracking version number'),
        ),
        migrations.AlterField(
            model_name='urinesample',
            name='created_by',
            field=models.ForeignKey(help_text='User account for the person logged in when this record was made/updated', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='urinesample',
            name='event',
            field=models.ForeignKey(help_text='Link to an event of type Urine', on_delete=django.db.models.deletion.CASCADE, to='samples.Event'),
        ),
        migrations.AlterField(
            model_name='urinesample',
            name='notes',
            field=models.TextField(blank=True, help_text='Deviation record', verbose_name='DM02 notes'),
        ),
        migrations.AlterField(
            model_name='urinesample',
            name='record_locked',
            field=models.BooleanField(default=False, help_text='Not presently implemented or used'),
        ),
        migrations.AlterField(
            model_name='urinesample',
            name='version',
            field=models.PositiveIntegerField(default=0, help_text='Internal tracking version number'),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='created_by',
            field=models.ForeignKey(help_text='User account for the person logged in when this record was made/updated', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='person',
            field=models.ForeignKey(help_text='Donor or Recipient that this worksheet relates to', on_delete=django.db.models.deletion.CASCADE, to='compare.OrganPerson'),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='record_locked',
            field=models.BooleanField(default=False, help_text='Not presently implemented or used'),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='version',
            field=models.PositiveIntegerField(default=0, help_text='Internal tracking version number'),
        ),
    ]
