# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 15:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compare', '0003_auto_20170215_1527'),
        ('samples', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='urinesample',
            name='created_by',
            field=models.ForeignKey(help_text='User account for the person logged in when this record was made/updated', on_delete=django.db.models.deletion.CASCADE, related_name='samples_urinesample_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='urinesample',
            name='event',
            field=models.ForeignKey(help_text='Link to an event of type Urine', on_delete=django.db.models.deletion.CASCADE, to='samples.Event'),
        ),
        migrations.AddField(
            model_name='urinesample',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compare.OrganPerson', verbose_name='US02 sample from'),
        ),
        migrations.AddField(
            model_name='tissuesample',
            name='created_by',
            field=models.ForeignKey(help_text='User account for the person logged in when this record was made/updated', on_delete=django.db.models.deletion.CASCADE, related_name='samples_tissuesample_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tissuesample',
            name='event',
            field=models.ForeignKey(help_text='Link to an event of type Tissue', on_delete=django.db.models.deletion.CASCADE, to='samples.Event'),
        ),
        migrations.AddField(
            model_name='tissuesample',
            name='organ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compare.Organ', verbose_name='TS01 sample from'),
        ),
        migrations.AddField(
            model_name='perfusatesample',
            name='created_by',
            field=models.ForeignKey(help_text='User account for the person logged in when this record was made/updated', on_delete=django.db.models.deletion.CASCADE, related_name='samples_perfusatesample_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='perfusatesample',
            name='event',
            field=models.ForeignKey(help_text='Link to an event of type Perfusate', on_delete=django.db.models.deletion.CASCADE, to='samples.Event'),
        ),
        migrations.AddField(
            model_name='perfusatesample',
            name='organ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compare.Organ', verbose_name='PS02 sample from'),
        ),
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(help_text='User account for the person logged in when this record was made/updated', on_delete=django.db.models.deletion.CASCADE, related_name='samples_event_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bloodsample',
            name='created_by',
            field=models.ForeignKey(help_text='User account for the person logged in when this record was made/updated', on_delete=django.db.models.deletion.CASCADE, related_name='samples_bloodsample_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bloodsample',
            name='event',
            field=models.ForeignKey(help_text='Link to an event of type Blood', on_delete=django.db.models.deletion.CASCADE, to='samples.Event'),
        ),
        migrations.AddField(
            model_name='bloodsample',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compare.OrganPerson', verbose_name='BS03 sample from'),
        ),
    ]
