# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0002_auto_20160427_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='worksheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samples.Worksheet'),
        ),
    ]
