# Generated by Django 2.0.1 on 2018-01-08 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0003_auto_20170405_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodsample',
            name='event',
            field=models.ForeignKey(help_text='Link to an event of type Blood', limit_choices_to={'type': 1}, on_delete=django.db.models.deletion.PROTECT, to='samples.Event'),
        ),
        migrations.AlterField(
            model_name='bloodsample',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compare.Patient', verbose_name='BS03 sample from'),
        ),
        migrations.AlterField(
            model_name='perfusatesample',
            name='event',
            field=models.ForeignKey(help_text='Link to an event of type Perfusate', limit_choices_to={'type': 3}, on_delete=django.db.models.deletion.PROTECT, to='samples.Event'),
        ),
        migrations.AlterField(
            model_name='perfusatesample',
            name='organ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compare.Organ', verbose_name='PS02 sample from'),
        ),
        migrations.AlterField(
            model_name='tissuesample',
            name='event',
            field=models.ForeignKey(help_text='Link to an event of type Tissue', limit_choices_to={'type': 4}, on_delete=django.db.models.deletion.PROTECT, to='samples.Event'),
        ),
        migrations.AlterField(
            model_name='tissuesample',
            name='organ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compare.Organ', verbose_name='TS01 sample from'),
        ),
        migrations.AlterField(
            model_name='urinesample',
            name='event',
            field=models.ForeignKey(help_text='Link to an event of type Urine', limit_choices_to={'type': 2}, on_delete=django.db.models.deletion.PROTECT, to='samples.Event'),
        ),
        migrations.AlterField(
            model_name='urinesample',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compare.Patient', verbose_name='US02 sample from'),
        ),
    ]
