# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 01:36
from __future__ import unicode_literals

from django.db import migrations, models
import livefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_locked', models.BooleanField(default=False, help_text='locked by the admin team')),
                ('live', livefield.fields.LiveField(default=True)),
                ('name', models.CharField(max_length=100, verbose_name='HO01 hospital name')),
                ('country', models.PositiveSmallIntegerField(choices=[(1, 'LOc01 United Kingdom'), (4, 'LOc02 Belgium'), (5, 'LOc03 Netherlands'), (10, 'LOc04 Albania'), (11, 'LOc05 Andorra'), (12, 'LOc06 Armenia'), (13, 'LOc07 Austria'), (14, 'LOc08 Azerbaijan'), (15, 'LOc09 Belarus'), (16, 'LOc10 Bosnia and Herzegovina'), (17, 'LOc11 Bulgaria'), (18, 'LOc12 Croatia'), (19, 'LOc13 Cyprus'), (20, 'LOc14 Czech Republic'), (21, 'LOc15 Denmark'), (22, 'LOc16 Estonia'), (23, 'LOc17 Finland'), (24, 'LOc18 France'), (25, 'LOc19 Georgia'), (26, 'LOc20 Germany'), (27, 'LOc21 Greece'), (28, 'LOc22 Hungary'), (29, 'LOc23 Iceland'), (30, 'LOc24 Ireland'), (31, 'LOc25 Italy'), (32, 'LOc26 Kazakhstan'), (33, 'LOc27 Kosovo'), (34, 'LOc28 Latvia'), (35, 'LOc29 Liechtenstein'), (36, 'LOc30 Lithuania'), (37, 'LOc31 Luxembourg'), (38, 'LOc32 Macedonia'), (39, 'LOc33 Malta'), (40, 'LOc34 Moldova'), (41, 'LOc35 Monaco'), (42, 'LOc36 Montenegro'), (43, 'LOc37 Norway'), (44, 'LOc38 Poland'), (45, 'LOc39 Portugal'), (46, 'LOc40 Romania'), (47, 'LOc41 Russia'), (48, 'LOc42 San Marino'), (49, 'LOc43 Serbia'), (50, 'LOc44 Slovakia'), (51, 'LOc45 Slovenia'), (52, 'LOc46 Spain'), (53, 'LOc47 Sweden'), (54, 'LOc48 Switzerland'), (55, 'LOc49 Turkey'), (56, 'LOc50 Ukraine')], verbose_name='HO02 country')),
                ('is_active', models.BooleanField(default=True, help_text='Not presently used/implemented. For legacy data when a location closes for use', verbose_name='HO03 is active')),
                ('is_project_site', models.BooleanField(default=False, verbose_name='HO04 is project site')),
            ],
            options={
                'verbose_name': 'HOm1 hospital',
                'verbose_name_plural': 'HOm2 hospitals',
                'ordering': ['country', 'name'],
            },
        ),
    ]
