# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 12:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='created_by',
            field=models.ForeignKey(help_text='User account for the person logged in when this record was made/updated', on_delete=django.db.models.deletion.CASCADE, related_name='locations_hospital_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
