# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-04 13:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_auto_20160427_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='created_by',
            field=models.ForeignKey(help_text='User account for the person logged in when this record was made/updated', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
