# Generated by Django 2.0.1 on 2018-01-08 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('followups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup1y',
            name='paper_form_was_the_source',
            field=models.NullBooleanField(verbose_name='OR97 Was this data entered from a paper record'),
        ),
        migrations.AddField(
            model_name='followup3m',
            name='paper_form_was_the_source',
            field=models.NullBooleanField(verbose_name='OR97 Was this data entered from a paper record'),
        ),
        migrations.AddField(
            model_name='followup6m',
            name='paper_form_was_the_source',
            field=models.NullBooleanField(verbose_name='OR97 Was this data entered from a paper record'),
        ),
        migrations.AddField(
            model_name='followupinitial',
            name='paper_form_was_the_source',
            field=models.NullBooleanField(verbose_name='OR97 Was this data entered from a paper record'),
        ),
        migrations.AlterField(
            model_name='followup1y',
            name='organ',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='followup_1y', to='compare.Organ', verbose_name='FY01 Trial id'),
        ),
        migrations.AlterField(
            model_name='followup1y',
            name='quality_of_life',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='followup_1y', to='health_economics.QualityOfLife', verbose_name='FY08 quality of life'),
        ),
        migrations.AlterField(
            model_name='followup3m',
            name='organ',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='followup_3m', to='compare.Organ', verbose_name='F301 Trial id'),
        ),
        migrations.AlterField(
            model_name='followup3m',
            name='quality_of_life',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='followup_3m', to='health_economics.QualityOfLife', verbose_name='F308 quality of life'),
        ),
        migrations.AlterField(
            model_name='followup6m',
            name='organ',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='followup_6m', to='compare.Organ', verbose_name='F601 Trial id'),
        ),
        migrations.AlterField(
            model_name='followupinitial',
            name='organ',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='followup_initial', to='compare.Organ', verbose_name='FI01 Trial id'),
        ),
    ]
