# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 12:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compare', '0003_auto_20170214_1232'),
        ('followups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health_economics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='followupinitial',
            name='created_by',
            field=models.ForeignKey(help_text='User account for the person logged in when this record was made/updated', on_delete=django.db.models.deletion.CASCADE, related_name='followups_followupinitial_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='followupinitial',
            name='organ',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='followup_initial', to='compare.Organ', verbose_name='FI01 Trial id'),
        ),
        migrations.AddField(
            model_name='followup6m',
            name='created_by',
            field=models.ForeignKey(help_text='User account for the person logged in when this record was made/updated', on_delete=django.db.models.deletion.CASCADE, related_name='followups_followup6m_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='followup6m',
            name='organ',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='followup_6m', to='compare.Organ', verbose_name='F601 Trial id'),
        ),
        migrations.AddField(
            model_name='followup3m',
            name='created_by',
            field=models.ForeignKey(help_text='User account for the person logged in when this record was made/updated', on_delete=django.db.models.deletion.CASCADE, related_name='followups_followup3m_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='followup3m',
            name='organ',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='followup_3m', to='compare.Organ', verbose_name='F301 Trial id'),
        ),
        migrations.AddField(
            model_name='followup3m',
            name='quality_of_life',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followup_3m', to='health_economics.QualityOfLife', verbose_name='F308 quality of life'),
        ),
        migrations.AddField(
            model_name='followup1y',
            name='created_by',
            field=models.ForeignKey(help_text='User account for the person logged in when this record was made/updated', on_delete=django.db.models.deletion.CASCADE, related_name='followups_followup1y_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='followup1y',
            name='organ',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='followup_1y', to='compare.Organ', verbose_name='FY01 Trial id'),
        ),
        migrations.AddField(
            model_name='followup1y',
            name='quality_of_life',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followup_1y', to='health_economics.QualityOfLife', verbose_name='FY08 quality of life'),
        ),
    ]
