# Generated by Django 2.1.7 on 2019-02-22 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('followups', '0002_auto_20180108_1433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='followup1y',
            options={'permissions': (('restrict_to_national', 'Can only use data from the same location country'), ('restrict_to_local', 'Can only use data from a specific location')), 'verbose_name': 'FYm1 1 Year FollowUp', 'verbose_name_plural': 'FYm2 1 Year FollowUps'},
        ),
        migrations.AlterModelOptions(
            name='followup3m',
            options={'permissions': (('restrict_to_national', 'Can only use data from the same location country'), ('restrict_to_local', 'Can only use data from a specific location')), 'verbose_name': 'F3m1 3 Month FollowUp', 'verbose_name_plural': 'F3m2 3 Month FollowUps'},
        ),
        migrations.AlterModelOptions(
            name='followup6m',
            options={'permissions': (('restrict_to_national', 'Can only use data from the same location country'), ('restrict_to_local', 'Can only use data from a specific location')), 'verbose_name': 'F6m1 6 Month FollowUp', 'verbose_name_plural': 'F6m2 6 Month FollowUps'},
        ),
        migrations.AlterModelOptions(
            name='followupinitial',
            options={'permissions': (('restrict_to_national', 'Can only use data from the same location country'), ('restrict_to_local', 'Can only use data from a specific location')), 'verbose_name': 'FIm1 Initial FollowUp', 'verbose_name_plural': 'FIm2 Initial FollowUps'},
        ),
    ]
