# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 17:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('followups', '0003_auto_20160122_1031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='followup1y',
            options={'verbose_name': 'FYm1 1 Year FollowUp', 'verbose_name_plural': 'FYm2 1 Year FollowUps'},
        ),
        migrations.AlterModelOptions(
            name='followup3m',
            options={'verbose_name': 'F3m1 3 Month FollowUp', 'verbose_name_plural': 'F3m2 3 Month FollowUps'},
        ),
        migrations.AlterModelOptions(
            name='followup6m',
            options={'verbose_name': 'F6m1 6 Month FollowUp', 'verbose_name_plural': 'F6m2 6 Month FollowUps'},
        ),
    ]
