# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 18:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('followups', '0003_auto_20160504_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup1y',
            name='quality_of_life',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followup_1y', to='health_economics.QualityOfLife', verbose_name='FY08 quality of life'),
        ),
        migrations.AlterField(
            model_name='followup3m',
            name='quality_of_life',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followup_3m', to='health_economics.QualityOfLife', verbose_name='F308 quality of life'),
        ),
    ]
