# Generated by Django 2.2.2 on 2019-06-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followups', '0003_auto_20190222_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup1y',
            name='record_locked',
            field=models.BooleanField(default=False, help_text='Locked by the admin team. This can only be reversed by the System Administrator'),
        ),
        migrations.AlterField(
            model_name='followup3m',
            name='record_locked',
            field=models.BooleanField(default=False, help_text='Locked by the admin team. This can only be reversed by the System Administrator'),
        ),
        migrations.AlterField(
            model_name='followup6m',
            name='record_locked',
            field=models.BooleanField(default=False, help_text='Locked by the admin team. This can only be reversed by the System Administrator'),
        ),
        migrations.AlterField(
            model_name='followupinitial',
            name='record_locked',
            field=models.BooleanField(default=False, help_text='Locked by the admin team. This can only be reversed by the System Administrator'),
        ),
    ]
