# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followups', '0004_auto_20160201_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followup1y',
            name='dialysis_requirement_1',
        ),
        migrations.RemoveField(
            model_name='followup3m',
            name='dialysis_requirement_1',
        ),
        migrations.RemoveField(
            model_name='followup6m',
            name='dialysis_requirement_1',
        ),
        migrations.RemoveField(
            model_name='followupinitial',
            name='dialysis_requirement_1',
        ),
        migrations.AddField(
            model_name='followup1y',
            name='last_dialysis_at',
            field=models.DateField(blank=True, null=True, verbose_name='FB10 date of last dialysis'),
        ),
        migrations.AddField(
            model_name='followup1y',
            name='on_dialysis_at_death',
            field=models.NullBooleanField(verbose_name='FB30 on dialysis at death'),
        ),
        migrations.AddField(
            model_name='followup3m',
            name='last_dialysis_at',
            field=models.DateField(blank=True, null=True, verbose_name='FB10 date of last dialysis'),
        ),
        migrations.AddField(
            model_name='followup3m',
            name='on_dialysis_at_death',
            field=models.NullBooleanField(verbose_name='FB30 on dialysis at death'),
        ),
        migrations.AddField(
            model_name='followup6m',
            name='last_dialysis_at',
            field=models.DateField(blank=True, null=True, verbose_name='FB10 date of last dialysis'),
        ),
        migrations.AddField(
            model_name='followup6m',
            name='on_dialysis_at_death',
            field=models.NullBooleanField(verbose_name='FB30 on dialysis at death'),
        ),
        migrations.AddField(
            model_name='followupinitial',
            name='last_dialysis_at',
            field=models.DateField(blank=True, null=True, verbose_name='FB10 date of last dialysis'),
        ),
        migrations.AddField(
            model_name='followupinitial',
            name='on_dialysis_at_death',
            field=models.NullBooleanField(verbose_name='FB30 on dialysis at death'),
        ),
    ]
