# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 16:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('followups', '0005_auto_20160226_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followup1y',
            name='urine_creatinine',
        ),
        migrations.RemoveField(
            model_name='followup1y',
            name='urine_creatinine_unit',
        ),
        migrations.RemoveField(
            model_name='followup3m',
            name='urine_creatinine',
        ),
        migrations.RemoveField(
            model_name='followup3m',
            name='urine_creatinine_unit',
        ),
        migrations.RemoveField(
            model_name='followup6m',
            name='urine_creatinine',
        ),
        migrations.RemoveField(
            model_name='followup6m',
            name='urine_creatinine_unit',
        ),
    ]
