# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('followups', '0007_auto_20160226_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followup1y',
            name='qol_anxiety',
        ),
        migrations.RemoveField(
            model_name='followup1y',
            name='qol_mobility',
        ),
        migrations.RemoveField(
            model_name='followup1y',
            name='qol_pain',
        ),
        migrations.RemoveField(
            model_name='followup1y',
            name='qol_selfcare',
        ),
        migrations.RemoveField(
            model_name='followup1y',
            name='qol_usual_activities',
        ),
        migrations.RemoveField(
            model_name='followup1y',
            name='vas_score',
        ),
        migrations.RemoveField(
            model_name='followup3m',
            name='qol_anxiety',
        ),
        migrations.RemoveField(
            model_name='followup3m',
            name='qol_mobility',
        ),
        migrations.RemoveField(
            model_name='followup3m',
            name='qol_pain',
        ),
        migrations.RemoveField(
            model_name='followup3m',
            name='qol_selfcare',
        ),
        migrations.RemoveField(
            model_name='followup3m',
            name='qol_usual_activities',
        ),
        migrations.RemoveField(
            model_name='followup3m',
            name='vas_score',
        ),
    ]
