# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 19:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('followups', '0009_auto_20160413_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup1y',
            name='created_by',
            field=models.ForeignKey(help_text='User account for the person logged in when this record was made/updated', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='followup1y',
            name='record_locked',
            field=models.BooleanField(default=False, help_text='Not presently implemented or used'),
        ),
        migrations.AlterField(
            model_name='followup1y',
            name='version',
            field=models.PositiveIntegerField(default=0, help_text='Internal tracking version number'),
        ),
        migrations.AlterField(
            model_name='followup3m',
            name='created_by',
            field=models.ForeignKey(help_text='User account for the person logged in when this record was made/updated', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='followup3m',
            name='record_locked',
            field=models.BooleanField(default=False, help_text='Not presently implemented or used'),
        ),
        migrations.AlterField(
            model_name='followup3m',
            name='version',
            field=models.PositiveIntegerField(default=0, help_text='Internal tracking version number'),
        ),
        migrations.AlterField(
            model_name='followup6m',
            name='created_by',
            field=models.ForeignKey(help_text='User account for the person logged in when this record was made/updated', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='followup6m',
            name='record_locked',
            field=models.BooleanField(default=False, help_text='Not presently implemented or used'),
        ),
        migrations.AlterField(
            model_name='followup6m',
            name='version',
            field=models.PositiveIntegerField(default=0, help_text='Internal tracking version number'),
        ),
        migrations.AlterField(
            model_name='followupinitial',
            name='created_by',
            field=models.ForeignKey(help_text='User account for the person logged in when this record was made/updated', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='followupinitial',
            name='record_locked',
            field=models.BooleanField(default=False, help_text='Not presently implemented or used'),
        ),
        migrations.AlterField(
            model_name='followupinitial',
            name='version',
            field=models.PositiveIntegerField(default=0, help_text='Internal tracking version number'),
        ),
    ]
