# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 09:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('followups', '0010_auto_20160427_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followup1y',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='followup1y',
            name='organ',
        ),
        migrations.RemoveField(
            model_name='followup1y',
            name='quality_of_life',
        ),
        migrations.RemoveField(
            model_name='followup3m',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='followup3m',
            name='organ',
        ),
        migrations.RemoveField(
            model_name='followup3m',
            name='quality_of_life',
        ),
        migrations.RemoveField(
            model_name='followup6m',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='followup6m',
            name='organ',
        ),
        migrations.RemoveField(
            model_name='followupinitial',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='followupinitial',
            name='organ',
        ),
        migrations.DeleteModel(
            name='FollowUp1Y',
        ),
        migrations.DeleteModel(
            name='FollowUp3M',
        ),
        migrations.DeleteModel(
            name='FollowUp6M',
        ),
        migrations.DeleteModel(
            name='FollowUpInitial',
        ),
    ]
