# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerfusionFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.FileField(blank=True, upload_to='perfusion_files')),
            ],
            options={
                'verbose_name': 'PFm1 perfusion machine file',
                'verbose_name_plural': 'PFm2 perfusion machine files',
            },
        ),
        migrations.CreateModel(
            name='PerfusionMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('machine_serial_number', models.CharField(max_length=50, verbose_name='PM01 machine serial number')),
                ('machine_reference_number', models.CharField(max_length=50, verbose_name='PM02 machine reference number')),
            ],
            options={
                'verbose_name': 'PMm1 perfusion machine',
                'verbose_name_plural': 'PMm2 perfusion machines',
            },
        ),
    ]
