# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_serial_number', models.CharField(max_length=50, verbose_name='PM01 machine serial number')),
                ('machine_reference_number', models.CharField(max_length=50, verbose_name='PM02 machine reference number')),
            ],
            options={
                'verbose_name': 'PMm1 perfusion machine',
                'verbose_name_plural': 'PMm2 perfusion machines',
            },
        ),
    ]
