# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 15:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perfusion_machine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='perfusionmachine',
            name='created_by',
            field=models.ForeignKey(help_text='User account for the person logged in when this record was made/updated', on_delete=django.db.models.deletion.CASCADE, related_name='perfusion_machine_perfusionmachine_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='perfusionfile',
            name='created_by',
            field=models.ForeignKey(help_text='User account for the person logged in when this record was made/updated', on_delete=django.db.models.deletion.CASCADE, related_name='perfusion_machine_perfusionfile_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='perfusionfile',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfusion_machine.PerfusionMachine', verbose_name='PF01 perfusion machine'),
        ),
    ]
