# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfusion_machine', '0002_auto_20160504_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfusionfile',
            name='file',
            field=models.FileField(blank=True, upload_to='perfusion_files'),
        ),
    ]
